server:
  port: 8764

spring:
  application:
    name: application-provader
  thymeleaf:
    #缓冲的配置
    cache: false
    check-template: true
    check-template-location: true
    #开启MVC thymeleaf 视图解析
    enabled: true
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    
    
  #配置数据源
  datasource:
  #   数据源基本配置
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/arch_test
      type: com.alibaba.druid.pool.DruidDataSource
  #   数据源其他配置
      druid:
        initial-size: 8
        min-idle: 1
        max-active: 20
        max-wait: 60000
        time-between-eviction-runsMillis: 60000
        min-evictable-idle-timeMillis: 300000
        validation-query: select 'x' FROM DUAL
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-open-prepared-statements: 20
        max-pool-prepared-statement-per-connection-size: 20
        filters: stat
        connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        use-global-data-source-stat: true

    
#指定mybatis映射文件的地址
mybatis:
  #配置文件的路径
  config-location: classpath:spring-mybatis.xml
  mapper-locations: classpath*:/com/dsfsys/proj/db/mapper/*/*.xml
  # mybatis自动扫描包中的实体类，自动定义别名，别名是类名(首字母大写或小写都可以,一般用小写)
  #type-aliases-package: com.dsfsys.proj.db.entity(mapper-locations扫描之后不用再次扫描，否则扫描两次报错)


#pagehelper分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-center1:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'

info:
  application.name: springcloud-microservice-eurekaclient1
  company.name: xxx
  build.artifactId: $project.artifactId$
  build.version:  $project.version$